Working on header
EbukaNweje/ebuka-portfolio pull request #1
Opened 2022-05-25 12:09 UTC by EbukaNweje

2022-05-25 17:12 UTC, EbukaNweje commented on index.html
> +      <h3>My Logo</h3>
like <h3><a>my Logo </a></h3>

2022-05-25 17:14 UTC, EbukaNweje commented on index.html
> +      <img src="./img/Menu.png" alt="Menu">
link 
<nav>
<img src="./img/Menu.png" alt="Menu">
</nav>

2022-05-25 18:03 UTC, topeogunleye commented on index.html
> +      <h3>My Logo</h3>
This is an example:
`<a>My Logo</a>`

2022-05-25 18:04 UTC, topeogunleye commented on index.html
> +      <img src="./img/Menu.png" alt="Menu">
This is an example:
```
<nav>
<img src="./img/Menu.png" alt="Menu">
</nav>
```

2022-05-25 19:16 UTC, Ismailco requested changes
### Hi @EbukaNweje,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 19:16 UTC, Ismailco commented on index.html
> +       </ul>
- [ ] [OPTIONAL] Each icons inside the ```ul``` should have a link ```a``` tag
e.g. ```<li><a href="Link-to-website"><i class="fa fa-hand-peace-o" aria-hidden="true"></i></a></li>```

2022-05-25 19:16 UTC, Ismailco commented on index.html
> +       <span>LET’S CONNECT</span>
- [ ] [OPTIONAL] The purpose of ```LET’S CONNECT``` is to call for action, so it should be a link, try to use ```<a>``` tag instead of ```<span>```

2022-05-25 19:16 UTC, Ismailco commented on css/style.css
> +header {
- [ ] [Optional] This is optional but for best practices, I suggest you use classes instead of tags to style your page

2022-05-25 19:16 UTC, Ismailco commented on css/style.css
> +header {
- [ ] [OPTIONAL] Please stick to the design as much as possible, including the margin/padding, width, and size

|Your design|Figm design|
|---|---|
|![Screenshot_20220525_200623](https://user-images.githubusercontent.com/25227022/170349497-81b13807-821b-4711-86f4-b9b9afd6d777.png)|![Screenshot_20220525_201307](https://user-images.githubusercontent.com/25227022/170349684-9ec3ab28-166f-452f-ace3-b8a4e5ab8781.png)|

2022-05-26 09:04 UTC, topeogunleye approved these changes
### Hi @EbukaNweje, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 09:08 UTC, merged