Desktop view
EbukaNweje/ebuka-portfolio pull request #5
Opened 2022-06-02 08:11 UTC by EbukaNweje

2022-06-02 09:54 UTC, dasileker requested changes
### **Hi @EbukaNweje,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## **Invalid Code Review Request**

You have submitted a project, that _**Your PR doesn't have descriptive details about the project, please add details and re-submit**_

![Capture web_2-6-2022_10527_github com](https://user-images.githubusercontent.com/61562626/171604952-5f60b0e7-12b1-4df8-afd7-6bae67b6bc58.jpeg)
![Capture web_2-6-2022_105310_gitlab com](https://user-images.githubusercontent.com/61562626/171604957-612b144e-f71a-4ee7-94af-5347b67a698b.jpeg)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-02 11:13 UTC, tufoinnkuo10 requested changes
Hi @EbukaNweje 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ app is responsive

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-02 11:13 UTC, tufoinnkuo10 commented on index.html
> +                </p>
- [ ] please make the text section of your cards responsive when switching from the mobile version to the desktop version or vice versa. 
your version.
![Screenshot (101)_LI](https://user-images.githubusercontent.com/65298048/171615613-e0d21ce9-fcfe-42b3-81da-7cec6f43d90f.jpg)

2022-06-02 11:13 UTC, tufoinnkuo10 commented on index.html
> +     </ul>
- [ ] kindly add a little left and right margin to your navigation bar..

2022-06-03 09:05 UTC, ishimwezachee approved these changes
Hi @EbukaNweje , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/nbvFVPiEiJH6JOGIok/giphy.gif"/>

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 09:06 UTC, merged